// A curated emoji set for the reaction picker's "+" grid, each tagged with a
// searchable name/keywords. Deliberately scoped to two themes — emotions/
// reactions and sports — rather than a broad grab-bag of every category
// (animals, food, weather, etc.), since those are what people actually react
// to a rec-league photo with.
export type EmojiEntry = {
  emoji: string;
  name: string;
  keywords?: string[];
};

export const EMOJI_DATA: EmojiEntry[] = [
  // Emotions / reactions — faces
  { emoji: '😂', name: 'laughing tears', keywords: ['lol', 'lmao', 'funny'] },
  { emoji: '🤣', name: 'rolling on the floor laughing', keywords: ['rofl', 'lmao'] },
  { emoji: '😭', name: 'crying', keywords: ['sob', 'sad', 'dead'] },
  { emoji: '😳', name: 'flushed', keywords: ['shocked', 'no way', 'omg'] },
  { emoji: '😬', name: 'grimacing', keywords: ['yikes', 'awkward'] },
  { emoji: '😅', name: 'sweat smile', keywords: ['nervous', 'phew'] },
  { emoji: '😤', name: 'triumph', keywords: ['huff', 'mad', 'proud'] },
  { emoji: '😡', name: 'angry', keywords: ['mad', 'rage'] },
  { emoji: '🥵', name: 'hot face', keywords: ['sweating', 'heat'] },
  { emoji: '🥶', name: 'cold face', keywords: ['freezing', 'ice'] },
  { emoji: '😴', name: 'sleeping', keywords: ['tired', 'zzz'] },
  { emoji: '🤡', name: 'clown', keywords: ['joke', 'silly'] },
  { emoji: '🫡', name: 'saluting face', keywords: ['salute', 'respect'] },
  { emoji: '🤔', name: 'thinking', keywords: ['hmm', 'suspicious'] },
  { emoji: '😍', name: 'heart eyes', keywords: ['love', 'crush'] },
  { emoji: '🤯', name: 'mind blown', keywords: ['shocked', 'wow'] },
  { emoji: '🙄', name: 'eye roll', keywords: ['whatever', 'annoyed'] },
  { emoji: '😏', name: 'smirk', keywords: ['sly', 'sneaky'] },
  { emoji: '🫠', name: 'melting face', keywords: ['dying', 'embarrassed'] },
  { emoji: '🥴', name: 'woozy', keywords: ['dizzy', 'drunk'] },
  { emoji: '😵‍💫', name: 'dizzy face', keywords: ['confused', 'spinning'] },
  { emoji: '🤢', name: 'nauseated', keywords: ['gross', 'sick'] },
  { emoji: '🤮', name: 'vomiting', keywords: ['gross', 'sick'] },
  { emoji: '😱', name: 'screaming', keywords: ['scared', 'shocked'] },
  { emoji: '💀', name: 'skull', keywords: ['dead', "im dead", 'lmao'] },
  { emoji: '☠️', name: 'skull and crossbones', keywords: ['danger', 'dead'] },
  { emoji: '🥲', name: 'smiling with tear', keywords: ['bittersweet'] },
  { emoji: '🫥', name: 'dotted line face', keywords: ['invisible', 'awkward'] },
  { emoji: '😇', name: 'angel', keywords: ['innocent', 'halo'] },
  { emoji: '🥳', name: 'party face', keywords: ['celebrate', 'birthday'] },
  { emoji: '😎', name: 'sunglasses cool', keywords: ['cool', 'swag'] },
  { emoji: '🤠', name: 'cowboy', keywords: ['yeehaw'] },
  { emoji: '🧐', name: 'monocle', keywords: ['curious', 'inspecting'] },
  { emoji: '😔', name: 'pensive', keywords: ['sad', 'down'] },
  { emoji: '🥺', name: 'pleading', keywords: ['puppy eyes', 'please'] },
  { emoji: '😩', name: 'weary', keywords: ['tired', 'exhausted'] },
  { emoji: '😖', name: 'confounded', keywords: ['frustrated'] },
  { emoji: '🤪', name: 'zany', keywords: ['crazy', 'wild'] },
  { emoji: '🫨', name: 'shaking face', keywords: ['shook', 'shocked'] },
  { emoji: '👻', name: 'ghost', keywords: ['spooky', 'boo'] },
  { emoji: '😆', name: 'grinning squinting', keywords: ['lol', 'laugh'] },
  { emoji: '😁', name: 'beaming', keywords: ['happy', 'grin'] },
  { emoji: '🤩', name: 'star struck', keywords: ['amazed', 'excited'] },
  { emoji: '🥹', name: 'holding back tears', keywords: ['emotional', 'proud'] },
  { emoji: '😐', name: 'neutral', keywords: ['meh', 'blank'] },
  { emoji: '😒', name: 'unamused', keywords: ['annoyed', 'over it'] },
  { emoji: '😑', name: 'expressionless', keywords: ['done', 'over it'] },
  { emoji: '🙃', name: 'upside down', keywords: ['sarcastic', 'silly'] },
  { emoji: '😷', name: 'sick face mask', keywords: ['ill', 'sick'] },
  { emoji: '🤕', name: 'head bandage', keywords: ['hurt', 'injury'] },
  { emoji: '🤒', name: 'thermometer face', keywords: ['sick', 'fever'] },
  { emoji: '😪', name: 'sleepy', keywords: ['tired', 'yawn'] },
  { emoji: '🫩', name: 'face with bags under eyes', keywords: ['exhausted', 'tired'] },
  { emoji: '😮‍💨', name: 'exhale', keywords: ['relief', 'sigh'] },
  { emoji: '🤬', name: 'cursing', keywords: ['furious', 'mad'] },
  { emoji: '😈', name: 'devil grin', keywords: ['evil', 'mischief'] },
  { emoji: '🥰', name: 'smiling with hearts', keywords: ['love', 'adore'] },
  { emoji: '😘', name: 'blowing a kiss', keywords: ['love', 'kiss'] },
  { emoji: '🤗', name: 'hugging', keywords: ['hug', 'support'] },
  { emoji: '😌', name: 'relieved', keywords: ['calm', 'content'] },

  // Emotions / reactions — hands & gestures
  { emoji: '👍', name: 'thumbs up', keywords: ['yes', 'good', 'approve'] },
  { emoji: '👎', name: 'thumbs down', keywords: ['no', 'bad', 'disapprove'] },
  { emoji: '👏', name: 'clapping', keywords: ['applause', 'respect'] },
  { emoji: '🙌', name: 'raised hands', keywords: ['praise', 'celebrate'] },
  { emoji: '🤝', name: 'handshake', keywords: ['deal', 'agreement'] },
  { emoji: '🙏', name: 'praying', keywords: ['please', 'thanks'] },
  { emoji: '🤙', name: 'call me', keywords: ['shaka', 'hang loose'] },
  { emoji: '✌️', name: 'peace sign', keywords: ['victory'] },
  { emoji: '🤌', name: 'pinched fingers', keywords: ['italian', 'what'] },
  { emoji: '👀', name: 'eyes', keywords: ['looking', 'suspicious'] },
  { emoji: '🖐️', name: 'raised hand', keywords: ['stop', 'high five'] },
  { emoji: '🫱', name: 'rightwards hand', keywords: ['reach'] },
  { emoji: '🫵', name: 'pointing at viewer', keywords: ['you'] },
  { emoji: '🤷', name: 'shrug', keywords: ['idk', 'whatever'] },
  { emoji: '🫶', name: 'heart hands', keywords: ['love', 'thanks'] },
  { emoji: '👊', name: 'fist bump', keywords: ['bump', 'punch'] },
  { emoji: '✋', name: 'hand', keywords: ['stop', 'high five'] },
  { emoji: '🤞', name: 'crossed fingers', keywords: ['luck', 'hope'] },
  { emoji: '🫰', name: 'money fingers', keywords: ['cash', 'rich'] },
  { emoji: '🫳', name: 'palm down hand', keywords: ['drop it'] },
  { emoji: '🫴', name: 'palm up hand', keywords: ['offer'] },
  { emoji: '👋', name: 'waving', keywords: ['hello', 'bye'] },
  { emoji: '🤚', name: 'back of hand', keywords: ['stop', 'raised'] },

  // Emotions / reactions — hearts
  { emoji: '❤️', name: 'red heart', keywords: ['love'] },
  { emoji: '🧡', name: 'orange heart', keywords: ['love'] },
  { emoji: '💛', name: 'yellow heart', keywords: ['love'] },
  { emoji: '💚', name: 'green heart', keywords: ['love'] },
  { emoji: '💙', name: 'blue heart', keywords: ['love'] },
  { emoji: '💜', name: 'purple heart', keywords: ['love'] },
  { emoji: '🖤', name: 'black heart', keywords: ['love', 'dark'] },
  { emoji: '💔', name: 'broken heart', keywords: ['heartbreak', 'sad'] },
  { emoji: '💕', name: 'two hearts', keywords: ['love'] },
  { emoji: '💖', name: 'sparkling heart', keywords: ['love'] },
  { emoji: '💘', name: 'heart with arrow', keywords: ['crush', 'love'] },
  { emoji: '💗', name: 'growing heart', keywords: ['love'] },
  { emoji: '💞', name: 'revolving hearts', keywords: ['love'] },
  { emoji: '❣️', name: 'heart exclamation', keywords: ['love'] },
  { emoji: '💟', name: 'heart decoration', keywords: ['love'] },

  // Sports / energy / achievement
  { emoji: '🔥', name: 'fire', keywords: ['lit', 'hot', 'flame'] },
  { emoji: '💯', name: 'hundred', keywords: ['perfect', 'agree'] },
  { emoji: '🎯', name: 'bullseye', keywords: ['target', 'on point'] },
  { emoji: '🏆', name: 'trophy', keywords: ['win', 'champion'] },
  { emoji: '🥇', name: 'gold medal', keywords: ['first', 'win'] },
  { emoji: '🥈', name: 'silver medal', keywords: ['second'] },
  { emoji: '🥉', name: 'bronze medal', keywords: ['third'] },
  { emoji: '🏅', name: 'sports medal', keywords: ['award'] },
  { emoji: '🚀', name: 'rocket', keywords: ['launch', 'fast'] },
  { emoji: '⚡', name: 'lightning', keywords: ['fast', 'electric', 'power'] },
  { emoji: '🎉', name: 'party popper', keywords: ['celebrate', 'confetti'] },
  { emoji: '🎊', name: 'confetti ball', keywords: ['party', 'celebrate'] },
  { emoji: '🐐', name: 'goat', keywords: ['greatest', 'goat', 'legend'] },
  { emoji: '🐌', name: 'snail', keywords: ['slow', 'choke'] },
  { emoji: '🍿', name: 'popcorn', keywords: ['watching', 'drama'] },
  { emoji: '🩹', name: 'bandage', keywords: ['injury', 'hurt'] },
  { emoji: '💪', name: 'flexed bicep', keywords: ['strong', 'muscle', 'gains'] },
  { emoji: '💥', name: 'boom', keywords: ['explosion', 'impact'] },
  { emoji: '💧', name: 'droplet', keywords: ['water', 'sweat'] },
  { emoji: '⏰', name: 'alarm clock', keywords: ['time', 'late'] },
  { emoji: '⏱️', name: 'stopwatch', keywords: ['timer', 'clutch'] },
  { emoji: '📈', name: 'chart up', keywords: ['improving', 'gains'] },
  { emoji: '📉', name: 'chart down', keywords: ['slump', 'decline'] },
  { emoji: '🚨', name: 'siren', keywords: ['alert', 'foul'] },
  { emoji: '🛑', name: 'stop sign', keywords: ['stop', 'foul'] },
  { emoji: '🚩', name: 'red flag', keywords: ['warning', 'penalty'] },
  { emoji: '🏁', name: 'checkered flag', keywords: ['finish', 'win'] },
  { emoji: '⭐', name: 'star', keywords: ['favorite', 'mvp'] },
  { emoji: '🌟', name: 'glowing star', keywords: ['favorite', 'standout'] },
  { emoji: '👑', name: 'crown', keywords: ['king', 'goat', 'champion'] },
  { emoji: '🥋', name: 'martial arts belt', keywords: ['discipline', 'sport'] },
  { emoji: '🦵', name: 'leg', keywords: ['kick', 'sport'] },
  { emoji: '🦶', name: 'foot', keywords: ['kick', 'sport'] },
  { emoji: '🥅', name: 'goal net', keywords: ['goal', 'score'] },
  { emoji: '🏟️', name: 'stadium', keywords: ['arena', 'game'] },
  { emoji: '🥍', name: 'lacrosse', keywords: ['sport'] },
  { emoji: '🛼', name: 'roller skate', keywords: ['sport'] },
  { emoji: '🏹', name: 'archery', keywords: ['sport'] },
  { emoji: '🤿', name: 'diving mask', keywords: ['snorkel', 'sport'] },
  { emoji: '🛹', name: 'skateboard', keywords: ['sport'] },

  // Sports / specific games
  { emoji: '🥎', name: 'softball', keywords: ['sport'] },
  { emoji: '⚾', name: 'baseball', keywords: ['sport'] },
  { emoji: '🏀', name: 'basketball', keywords: ['sport', 'hoops'] },
  { emoji: '⚽', name: 'soccer', keywords: ['football', 'sport'] },
  { emoji: '🏈', name: 'football', keywords: ['sport'] },
  { emoji: '🎾', name: 'tennis', keywords: ['sport'] },
  { emoji: '🏓', name: 'ping pong', keywords: ['table tennis', 'sport'] },
  { emoji: '🏐', name: 'volleyball', keywords: ['sport'] },
  { emoji: '🏸', name: 'badminton', keywords: ['sport'] },
  { emoji: '🥊', name: 'boxing glove', keywords: ['fight', 'sport'] },
  { emoji: '🏄', name: 'surfing', keywords: ['surf', 'sport'] },
  { emoji: '🏃', name: 'running', keywords: ['run', 'sport'] },
  { emoji: '🚴', name: 'cycling', keywords: ['bike', 'sport'] },
  { emoji: '🏊', name: 'swimming', keywords: ['swim', 'sport'] },
  { emoji: '🎳', name: 'bowling', keywords: ['sport'] },
  { emoji: '🥏', name: 'flying disc', keywords: ['frisbee', 'sport'] },
  { emoji: '🏒', name: 'hockey', keywords: ['sport'] },
  { emoji: '🎿', name: 'skiing', keywords: ['ski', 'sport'] },
  { emoji: '🤾', name: 'handball', keywords: ['sport'] },
  { emoji: '🚣', name: 'rowing', keywords: ['sport'] },
  { emoji: '🧗', name: 'climbing', keywords: ['sport'] },
  { emoji: '🤺', name: 'fencing', keywords: ['sport'] },
  { emoji: '🏋️', name: 'weightlifting', keywords: ['gym', 'sport'] },
];
